= RESTful 8-bit Catalog API Specification

:doctype: book

== Find a game by id

A `GET` request is used to find a NES game by ID

operation::get-game-by-id[snippets='curl-request,http-request,http-response,response-fields']




== Get all games

A `GET` request is used to find all NES games

operation::get-games[snippets='curl-request,http-request,http-response,response-fields']




== Get all developers

A `GET` request is used to find all distinct names of the developer companies of the NES games

operation::get-developers[snippets='curl-request,http-request,http-response,response-fields']




== Find all games by developer

A `GET` request is used to find all NES game by developer

operation::get-games-by-developer[snippets='curl-request,http-request,http-response,response-fields']





== Get all publishers

A `GET` request is used to find all distinct names of the publisher companies of the NES games

operation::get-publishers[snippets='curl-request,http-request,http-response,response-fields']




== Find all games by publisher

A `GET` request is used to find all NES game by publisher

operation::get-games-by-publisher[snippets='curl-request,http-request,http-response,response-fields']




== Get all categories

A `GET` request is used to find all categories of the NES games

operation::get-categories[snippets='curl-request,http-request,http-response,response-fields']

