package api._bit.catalog.domain;

public enum GameCategory {
    ACTION, ADULT, ADVENTURE, EDUCATIONAL, FIGHTING, PUZZLE, RACING,
    ROLE_PLAYING, SHOOTER, SIMULATION, SPORTS, STRATEGY, TRADITIONAL, VARIOUS
}
